# Security Configuration for Dependabot PRs
# This file defines security policies and secret management

security:
  # Secrets that are safe to expose to Dependabot
  safe_secrets:
    - GITHUB_TOKEN
    - NPM_TOKEN  # Only if using npm publish
  
  # Secrets that should never be exposed to Dependabot
  restricted_secrets:
    - TENDERLY_API_KEY
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - DATABASE_URL
    - JWT_SECRET
  
  # Security checks for Dependabot PRs
  checks:
    - name: "Secret Exposure Detection"
      tool: "gitleaks"
      severity: "error"
    
    - name: "CodeQL Analysis"
      tool: "codeql"
      severity: "warning"
    
    - name: "Semgrep Security Scan"
      tool: "semgrep"
      severity: "warning"
    
    - name: "Dependency Vulnerability Scan"
      tool: "npm audit"
      severity: "error"
  
  # Allowed patterns for Dependabot PRs
  allowed_patterns:
    - "package.json"
    - "package-lock.json"
    - "pnpm-lock.yaml"
    - "yarn.lock"
    - "**/*.d.ts"
    - "**/node_modules/**"
  
  # Blocked patterns that indicate potential security issues
  blocked_patterns:
    - "echo.*secrets"
    - "console.log.*secrets"
    - "TENDERLY_API_KEY.*[A-Za-z0-9]"
    - "AWS_.*KEY.*[A-Za-z0-9]"
    - "DATABASE_URL.*[A-Za-z0-9]" 