/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SealEngineRouteImport } from './routes/seal-engine'
import { Route as DevRouteImport } from './routes/dev'
import { Route as BatchTransactionsLegalNoticeRouteImport } from './routes/batch-transactions-legal-notice'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellVaultsRouteImport } from './routes/_shell.vaults'
import { Route as ShellStakeRouteImport } from './routes/_shell.stake'
import { Route as ShellSavingsRouteImport } from './routes/_shell.savings'
import { Route as ShellRewardsRouteImport } from './routes/_shell.rewards'
import { Route as ShellPortfolioRouteImport } from './routes/_shell.portfolio'
import { Route as ShellFixedRouteImport } from './routes/_shell.fixed'
import { Route as ShellExpertRouteImport } from './routes/_shell.expert'
import { Route as ShellEarnRouteImport } from './routes/_shell.earn'
import { Route as ShellConvertRouteImport } from './routes/_shell.convert'
import { Route as ShellRewardsRewardContractRouteImport } from './routes/_shell.rewards.$rewardContract'
import { Route as ShellExpertStusdsRouteImport } from './routes/_shell.expert.stusds'
import { Route as ShellConvertUpgradeRouteImport } from './routes/_shell.convert.upgrade'
import { Route as ShellConvertTradeRouteImport } from './routes/_shell.convert.trade'
import { Route as ShellConvertPsmRouteImport } from './routes/_shell.convert.psm'
import { Route as ShellVaultsProviderVaultAddressRouteImport } from './routes/_shell.vaults.$provider.$vaultAddress'
import { Route as ShellFixedMarketMarketAddressRouteImport } from './routes/_shell.fixed.market.$marketAddress'

const SealEngineRoute = SealEngineRouteImport.update({
  id: '/seal-engine',
  path: '/seal-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchTransactionsLegalNoticeRoute =
  BatchTransactionsLegalNoticeRouteImport.update({
    id: '/batch-transactions-legal-notice',
    path: '/batch-transactions-legal-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVaultsRoute = ShellVaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStakeRoute = ShellStakeRouteImport.update({
  id: '/stake',
  path: '/stake',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSavingsRoute = ShellSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRewardsRoute = ShellRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPortfolioRoute = ShellPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFixedRoute = ShellFixedRouteImport.update({
  id: '/fixed',
  path: '/fixed',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExpertRoute = ShellExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEarnRoute = ShellEarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConvertRoute = ShellConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRewardsRewardContractRoute =
  ShellRewardsRewardContractRouteImport.update({
    id: '/$rewardContract',
    path: '/$rewardContract',
    getParentRoute: () => ShellRewardsRoute,
  } as any)
const ShellExpertStusdsRoute = ShellExpertStusdsRouteImport.update({
  id: '/stusds',
  path: '/stusds',
  getParentRoute: () => ShellExpertRoute,
} as any)
const ShellConvertUpgradeRoute = ShellConvertUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => ShellConvertRoute,
} as any)
const ShellConvertTradeRoute = ShellConvertTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => ShellConvertRoute,
} as any)
const ShellConvertPsmRoute = ShellConvertPsmRouteImport.update({
  id: '/psm',
  path: '/psm',
  getParentRoute: () => ShellConvertRoute,
} as any)
const ShellVaultsProviderVaultAddressRoute =
  ShellVaultsProviderVaultAddressRouteImport.update({
    id: '/$provider/$vaultAddress',
    path: '/$provider/$vaultAddress',
    getParentRoute: () => ShellVaultsRoute,
  } as any)
const ShellFixedMarketMarketAddressRoute =
  ShellFixedMarketMarketAddressRouteImport.update({
    id: '/market/$marketAddress',
    path: '/market/$marketAddress',
    getParentRoute: () => ShellFixedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/batch-transactions-legal-notice': typeof BatchTransactionsLegalNoticeRoute
  '/dev': typeof DevRoute
  '/seal-engine': typeof SealEngineRoute
  '/convert': typeof ShellConvertRouteWithChildren
  '/earn': typeof ShellEarnRoute
  '/expert': typeof ShellExpertRouteWithChildren
  '/fixed': typeof ShellFixedRouteWithChildren
  '/portfolio': typeof ShellPortfolioRoute
  '/rewards': typeof ShellRewardsRouteWithChildren
  '/savings': typeof ShellSavingsRoute
  '/stake': typeof ShellStakeRoute
  '/vaults': typeof ShellVaultsRouteWithChildren
  '/convert/psm': typeof ShellConvertPsmRoute
  '/convert/trade': typeof ShellConvertTradeRoute
  '/convert/upgrade': typeof ShellConvertUpgradeRoute
  '/expert/stusds': typeof ShellExpertStusdsRoute
  '/rewards/$rewardContract': typeof ShellRewardsRewardContractRoute
  '/fixed/market/$marketAddress': typeof ShellFixedMarketMarketAddressRoute
  '/vaults/$provider/$vaultAddress': typeof ShellVaultsProviderVaultAddressRoute
}
export interface FileRoutesByTo {
  '/batch-transactions-legal-notice': typeof BatchTransactionsLegalNoticeRoute
  '/dev': typeof DevRoute
  '/seal-engine': typeof SealEngineRoute
  '/convert': typeof ShellConvertRouteWithChildren
  '/earn': typeof ShellEarnRoute
  '/expert': typeof ShellExpertRouteWithChildren
  '/fixed': typeof ShellFixedRouteWithChildren
  '/portfolio': typeof ShellPortfolioRoute
  '/rewards': typeof ShellRewardsRouteWithChildren
  '/savings': typeof ShellSavingsRoute
  '/stake': typeof ShellStakeRoute
  '/vaults': typeof ShellVaultsRouteWithChildren
  '/': typeof ShellIndexRoute
  '/convert/psm': typeof ShellConvertPsmRoute
  '/convert/trade': typeof ShellConvertTradeRoute
  '/convert/upgrade': typeof ShellConvertUpgradeRoute
  '/expert/stusds': typeof ShellExpertStusdsRoute
  '/rewards/$rewardContract': typeof ShellRewardsRewardContractRoute
  '/fixed/market/$marketAddress': typeof ShellFixedMarketMarketAddressRoute
  '/vaults/$provider/$vaultAddress': typeof ShellVaultsProviderVaultAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/batch-transactions-legal-notice': typeof BatchTransactionsLegalNoticeRoute
  '/dev': typeof DevRoute
  '/seal-engine': typeof SealEngineRoute
  '/_shell/convert': typeof ShellConvertRouteWithChildren
  '/_shell/earn': typeof ShellEarnRoute
  '/_shell/expert': typeof ShellExpertRouteWithChildren
  '/_shell/fixed': typeof ShellFixedRouteWithChildren
  '/_shell/portfolio': typeof ShellPortfolioRoute
  '/_shell/rewards': typeof ShellRewardsRouteWithChildren
  '/_shell/savings': typeof ShellSavingsRoute
  '/_shell/stake': typeof ShellStakeRoute
  '/_shell/vaults': typeof ShellVaultsRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
  '/_shell/convert/psm': typeof ShellConvertPsmRoute
  '/_shell/convert/trade': typeof ShellConvertTradeRoute
  '/_shell/convert/upgrade': typeof ShellConvertUpgradeRoute
  '/_shell/expert/stusds': typeof ShellExpertStusdsRoute
  '/_shell/rewards/$rewardContract': typeof ShellRewardsRewardContractRoute
  '/_shell/fixed/market/$marketAddress': typeof ShellFixedMarketMarketAddressRoute
  '/_shell/vaults/$provider/$vaultAddress': typeof ShellVaultsProviderVaultAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batch-transactions-legal-notice'
    | '/dev'
    | '/seal-engine'
    | '/convert'
    | '/earn'
    | '/expert'
    | '/fixed'
    | '/portfolio'
    | '/rewards'
    | '/savings'
    | '/stake'
    | '/vaults'
    | '/convert/psm'
    | '/convert/trade'
    | '/convert/upgrade'
    | '/expert/stusds'
    | '/rewards/$rewardContract'
    | '/fixed/market/$marketAddress'
    | '/vaults/$provider/$vaultAddress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/batch-transactions-legal-notice'
    | '/dev'
    | '/seal-engine'
    | '/convert'
    | '/earn'
    | '/expert'
    | '/fixed'
    | '/portfolio'
    | '/rewards'
    | '/savings'
    | '/stake'
    | '/vaults'
    | '/'
    | '/convert/psm'
    | '/convert/trade'
    | '/convert/upgrade'
    | '/expert/stusds'
    | '/rewards/$rewardContract'
    | '/fixed/market/$marketAddress'
    | '/vaults/$provider/$vaultAddress'
  id:
    | '__root__'
    | '/_shell'
    | '/batch-transactions-legal-notice'
    | '/dev'
    | '/seal-engine'
    | '/_shell/convert'
    | '/_shell/earn'
    | '/_shell/expert'
    | '/_shell/fixed'
    | '/_shell/portfolio'
    | '/_shell/rewards'
    | '/_shell/savings'
    | '/_shell/stake'
    | '/_shell/vaults'
    | '/_shell/'
    | '/_shell/convert/psm'
    | '/_shell/convert/trade'
    | '/_shell/convert/upgrade'
    | '/_shell/expert/stusds'
    | '/_shell/rewards/$rewardContract'
    | '/_shell/fixed/market/$marketAddress'
    | '/_shell/vaults/$provider/$vaultAddress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  BatchTransactionsLegalNoticeRoute: typeof BatchTransactionsLegalNoticeRoute
  DevRoute: typeof DevRoute
  SealEngineRoute: typeof SealEngineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seal-engine': {
      id: '/seal-engine'
      path: '/seal-engine'
      fullPath: '/seal-engine'
      preLoaderRoute: typeof SealEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch-transactions-legal-notice': {
      id: '/batch-transactions-legal-notice'
      path: '/batch-transactions-legal-notice'
      fullPath: '/batch-transactions-legal-notice'
      preLoaderRoute: typeof BatchTransactionsLegalNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/vaults': {
      id: '/_shell/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof ShellVaultsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/stake': {
      id: '/_shell/stake'
      path: '/stake'
      fullPath: '/stake'
      preLoaderRoute: typeof ShellStakeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/savings': {
      id: '/_shell/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof ShellSavingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/rewards': {
      id: '/_shell/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof ShellRewardsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/portfolio': {
      id: '/_shell/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof ShellPortfolioRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/fixed': {
      id: '/_shell/fixed'
      path: '/fixed'
      fullPath: '/fixed'
      preLoaderRoute: typeof ShellFixedRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/expert': {
      id: '/_shell/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ShellExpertRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/earn': {
      id: '/_shell/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof ShellEarnRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/convert': {
      id: '/_shell/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ShellConvertRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/rewards/$rewardContract': {
      id: '/_shell/rewards/$rewardContract'
      path: '/$rewardContract'
      fullPath: '/rewards/$rewardContract'
      preLoaderRoute: typeof ShellRewardsRewardContractRouteImport
      parentRoute: typeof ShellRewardsRoute
    }
    '/_shell/expert/stusds': {
      id: '/_shell/expert/stusds'
      path: '/stusds'
      fullPath: '/expert/stusds'
      preLoaderRoute: typeof ShellExpertStusdsRouteImport
      parentRoute: typeof ShellExpertRoute
    }
    '/_shell/convert/upgrade': {
      id: '/_shell/convert/upgrade'
      path: '/upgrade'
      fullPath: '/convert/upgrade'
      preLoaderRoute: typeof ShellConvertUpgradeRouteImport
      parentRoute: typeof ShellConvertRoute
    }
    '/_shell/convert/trade': {
      id: '/_shell/convert/trade'
      path: '/trade'
      fullPath: '/convert/trade'
      preLoaderRoute: typeof ShellConvertTradeRouteImport
      parentRoute: typeof ShellConvertRoute
    }
    '/_shell/convert/psm': {
      id: '/_shell/convert/psm'
      path: '/psm'
      fullPath: '/convert/psm'
      preLoaderRoute: typeof ShellConvertPsmRouteImport
      parentRoute: typeof ShellConvertRoute
    }
    '/_shell/vaults/$provider/$vaultAddress': {
      id: '/_shell/vaults/$provider/$vaultAddress'
      path: '/$provider/$vaultAddress'
      fullPath: '/vaults/$provider/$vaultAddress'
      preLoaderRoute: typeof ShellVaultsProviderVaultAddressRouteImport
      parentRoute: typeof ShellVaultsRoute
    }
    '/_shell/fixed/market/$marketAddress': {
      id: '/_shell/fixed/market/$marketAddress'
      path: '/market/$marketAddress'
      fullPath: '/fixed/market/$marketAddress'
      preLoaderRoute: typeof ShellFixedMarketMarketAddressRouteImport
      parentRoute: typeof ShellFixedRoute
    }
  }
}

interface ShellConvertRouteChildren {
  ShellConvertPsmRoute: typeof ShellConvertPsmRoute
  ShellConvertTradeRoute: typeof ShellConvertTradeRoute
  ShellConvertUpgradeRoute: typeof ShellConvertUpgradeRoute
}

const ShellConvertRouteChildren: ShellConvertRouteChildren = {
  ShellConvertPsmRoute: ShellConvertPsmRoute,
  ShellConvertTradeRoute: ShellConvertTradeRoute,
  ShellConvertUpgradeRoute: ShellConvertUpgradeRoute,
}

const ShellConvertRouteWithChildren = ShellConvertRoute._addFileChildren(
  ShellConvertRouteChildren,
)

interface ShellExpertRouteChildren {
  ShellExpertStusdsRoute: typeof ShellExpertStusdsRoute
}

const ShellExpertRouteChildren: ShellExpertRouteChildren = {
  ShellExpertStusdsRoute: ShellExpertStusdsRoute,
}

const ShellExpertRouteWithChildren = ShellExpertRoute._addFileChildren(
  ShellExpertRouteChildren,
)

interface ShellFixedRouteChildren {
  ShellFixedMarketMarketAddressRoute: typeof ShellFixedMarketMarketAddressRoute
}

const ShellFixedRouteChildren: ShellFixedRouteChildren = {
  ShellFixedMarketMarketAddressRoute: ShellFixedMarketMarketAddressRoute,
}

const ShellFixedRouteWithChildren = ShellFixedRoute._addFileChildren(
  ShellFixedRouteChildren,
)

interface ShellRewardsRouteChildren {
  ShellRewardsRewardContractRoute: typeof ShellRewardsRewardContractRoute
}

const ShellRewardsRouteChildren: ShellRewardsRouteChildren = {
  ShellRewardsRewardContractRoute: ShellRewardsRewardContractRoute,
}

const ShellRewardsRouteWithChildren = ShellRewardsRoute._addFileChildren(
  ShellRewardsRouteChildren,
)

interface ShellVaultsRouteChildren {
  ShellVaultsProviderVaultAddressRoute: typeof ShellVaultsProviderVaultAddressRoute
}

const ShellVaultsRouteChildren: ShellVaultsRouteChildren = {
  ShellVaultsProviderVaultAddressRoute: ShellVaultsProviderVaultAddressRoute,
}

const ShellVaultsRouteWithChildren = ShellVaultsRoute._addFileChildren(
  ShellVaultsRouteChildren,
)

interface ShellRouteChildren {
  ShellConvertRoute: typeof ShellConvertRouteWithChildren
  ShellEarnRoute: typeof ShellEarnRoute
  ShellExpertRoute: typeof ShellExpertRouteWithChildren
  ShellFixedRoute: typeof ShellFixedRouteWithChildren
  ShellPortfolioRoute: typeof ShellPortfolioRoute
  ShellRewardsRoute: typeof ShellRewardsRouteWithChildren
  ShellSavingsRoute: typeof ShellSavingsRoute
  ShellStakeRoute: typeof ShellStakeRoute
  ShellVaultsRoute: typeof ShellVaultsRouteWithChildren
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellConvertRoute: ShellConvertRouteWithChildren,
  ShellEarnRoute: ShellEarnRoute,
  ShellExpertRoute: ShellExpertRouteWithChildren,
  ShellFixedRoute: ShellFixedRouteWithChildren,
  ShellPortfolioRoute: ShellPortfolioRoute,
  ShellRewardsRoute: ShellRewardsRouteWithChildren,
  ShellSavingsRoute: ShellSavingsRoute,
  ShellStakeRoute: ShellStakeRoute,
  ShellVaultsRoute: ShellVaultsRouteWithChildren,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  BatchTransactionsLegalNoticeRoute: BatchTransactionsLegalNoticeRoute,
  DevRoute: DevRoute,
  SealEngineRoute: SealEngineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
