/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SealEngineRouteImport } from './routes/seal-engine'
import { Route as DevRouteImport } from './routes/dev'
import { Route as BatchTransactionsLegalNoticeRouteImport } from './routes/batch-transactions-legal-notice'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellStakeRouteImport } from './routes/_shell.stake'
import { Route as ShellPortfolioRouteImport } from './routes/_shell.portfolio'
import { Route as ShellConvertRouteImport } from './routes/_shell.convert'
import { Route as ShellEarnIndexRouteImport } from './routes/_shell.earn.index'
import { Route as ShellEarnVaultsRouteImport } from './routes/_shell.earn.vaults'
import { Route as ShellEarnSavingsRouteImport } from './routes/_shell.earn.savings'
import { Route as ShellEarnRewardsRouteImport } from './routes/_shell.earn.rewards'
import { Route as ShellEarnFixedRouteImport } from './routes/_shell.earn.fixed'
import { Route as ShellEarnExpertRouteImport } from './routes/_shell.earn.expert'
import { Route as ShellConvertUpgradeRouteImport } from './routes/_shell.convert.upgrade'
import { Route as ShellConvertTradeRouteImport } from './routes/_shell.convert.trade'
import { Route as ShellConvertPsmRouteImport } from './routes/_shell.convert.psm'
import { Route as ShellEarnRewardsRewardContractRouteImport } from './routes/_shell.earn.rewards.$rewardContract'
import { Route as ShellEarnExpertStusdsRouteImport } from './routes/_shell.earn.expert.stusds'
import { Route as ShellEarnVaultsProviderVaultAddressRouteImport } from './routes/_shell.earn.vaults.$provider.$vaultAddress'
import { Route as ShellEarnFixedMarketMarketAddressRouteImport } from './routes/_shell.earn.fixed.market.$marketAddress'

const SealEngineRoute = SealEngineRouteImport.update({
  id: '/seal-engine',
  path: '/seal-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchTransactionsLegalNoticeRoute =
  BatchTransactionsLegalNoticeRouteImport.update({
    id: '/batch-transactions-legal-notice',
    path: '/batch-transactions-legal-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStakeRoute = ShellStakeRouteImport.update({
  id: '/stake',
  path: '/stake',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPortfolioRoute = ShellPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConvertRoute = ShellConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEarnIndexRoute = ShellEarnIndexRouteImport.update({
  id: '/earn/',
  path: '/earn/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEarnVaultsRoute = ShellEarnVaultsRouteImport.update({
  id: '/earn/vaults',
  path: '/earn/vaults',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEarnSavingsRoute = ShellEarnSavingsRouteImport.update({
  id: '/earn/savings',
  path: '/earn/savings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEarnRewardsRoute = ShellEarnRewardsRouteImport.update({
  id: '/earn/rewards',
  path: '/earn/rewards',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEarnFixedRoute = ShellEarnFixedRouteImport.update({
  id: '/earn/fixed',
  path: '/earn/fixed',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEarnExpertRoute = ShellEarnExpertRouteImport.update({
  id: '/earn/expert',
  path: '/earn/expert',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConvertUpgradeRoute = ShellConvertUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => ShellConvertRoute,
} as any)
const ShellConvertTradeRoute = ShellConvertTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => ShellConvertRoute,
} as any)
const ShellConvertPsmRoute = ShellConvertPsmRouteImport.update({
  id: '/psm',
  path: '/psm',
  getParentRoute: () => ShellConvertRoute,
} as any)
const ShellEarnRewardsRewardContractRoute =
  ShellEarnRewardsRewardContractRouteImport.update({
    id: '/$rewardContract',
    path: '/$rewardContract',
    getParentRoute: () => ShellEarnRewardsRoute,
  } as any)
const ShellEarnExpertStusdsRoute = ShellEarnExpertStusdsRouteImport.update({
  id: '/stusds',
  path: '/stusds',
  getParentRoute: () => ShellEarnExpertRoute,
} as any)
const ShellEarnVaultsProviderVaultAddressRoute =
  ShellEarnVaultsProviderVaultAddressRouteImport.update({
    id: '/$provider/$vaultAddress',
    path: '/$provider/$vaultAddress',
    getParentRoute: () => ShellEarnVaultsRoute,
  } as any)
const ShellEarnFixedMarketMarketAddressRoute =
  ShellEarnFixedMarketMarketAddressRouteImport.update({
    id: '/market/$marketAddress',
    path: '/market/$marketAddress',
    getParentRoute: () => ShellEarnFixedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/batch-transactions-legal-notice': typeof BatchTransactionsLegalNoticeRoute
  '/dev': typeof DevRoute
  '/seal-engine': typeof SealEngineRoute
  '/convert': typeof ShellConvertRouteWithChildren
  '/portfolio': typeof ShellPortfolioRoute
  '/stake': typeof ShellStakeRoute
  '/convert/psm': typeof ShellConvertPsmRoute
  '/convert/trade': typeof ShellConvertTradeRoute
  '/convert/upgrade': typeof ShellConvertUpgradeRoute
  '/earn/expert': typeof ShellEarnExpertRouteWithChildren
  '/earn/fixed': typeof ShellEarnFixedRouteWithChildren
  '/earn/rewards': typeof ShellEarnRewardsRouteWithChildren
  '/earn/savings': typeof ShellEarnSavingsRoute
  '/earn/vaults': typeof ShellEarnVaultsRouteWithChildren
  '/earn/': typeof ShellEarnIndexRoute
  '/earn/expert/stusds': typeof ShellEarnExpertStusdsRoute
  '/earn/rewards/$rewardContract': typeof ShellEarnRewardsRewardContractRoute
  '/earn/fixed/market/$marketAddress': typeof ShellEarnFixedMarketMarketAddressRoute
  '/earn/vaults/$provider/$vaultAddress': typeof ShellEarnVaultsProviderVaultAddressRoute
}
export interface FileRoutesByTo {
  '/batch-transactions-legal-notice': typeof BatchTransactionsLegalNoticeRoute
  '/dev': typeof DevRoute
  '/seal-engine': typeof SealEngineRoute
  '/convert': typeof ShellConvertRouteWithChildren
  '/portfolio': typeof ShellPortfolioRoute
  '/stake': typeof ShellStakeRoute
  '/': typeof ShellIndexRoute
  '/convert/psm': typeof ShellConvertPsmRoute
  '/convert/trade': typeof ShellConvertTradeRoute
  '/convert/upgrade': typeof ShellConvertUpgradeRoute
  '/earn/expert': typeof ShellEarnExpertRouteWithChildren
  '/earn/fixed': typeof ShellEarnFixedRouteWithChildren
  '/earn/rewards': typeof ShellEarnRewardsRouteWithChildren
  '/earn/savings': typeof ShellEarnSavingsRoute
  '/earn/vaults': typeof ShellEarnVaultsRouteWithChildren
  '/earn': typeof ShellEarnIndexRoute
  '/earn/expert/stusds': typeof ShellEarnExpertStusdsRoute
  '/earn/rewards/$rewardContract': typeof ShellEarnRewardsRewardContractRoute
  '/earn/fixed/market/$marketAddress': typeof ShellEarnFixedMarketMarketAddressRoute
  '/earn/vaults/$provider/$vaultAddress': typeof ShellEarnVaultsProviderVaultAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/batch-transactions-legal-notice': typeof BatchTransactionsLegalNoticeRoute
  '/dev': typeof DevRoute
  '/seal-engine': typeof SealEngineRoute
  '/_shell/convert': typeof ShellConvertRouteWithChildren
  '/_shell/portfolio': typeof ShellPortfolioRoute
  '/_shell/stake': typeof ShellStakeRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/convert/psm': typeof ShellConvertPsmRoute
  '/_shell/convert/trade': typeof ShellConvertTradeRoute
  '/_shell/convert/upgrade': typeof ShellConvertUpgradeRoute
  '/_shell/earn/expert': typeof ShellEarnExpertRouteWithChildren
  '/_shell/earn/fixed': typeof ShellEarnFixedRouteWithChildren
  '/_shell/earn/rewards': typeof ShellEarnRewardsRouteWithChildren
  '/_shell/earn/savings': typeof ShellEarnSavingsRoute
  '/_shell/earn/vaults': typeof ShellEarnVaultsRouteWithChildren
  '/_shell/earn/': typeof ShellEarnIndexRoute
  '/_shell/earn/expert/stusds': typeof ShellEarnExpertStusdsRoute
  '/_shell/earn/rewards/$rewardContract': typeof ShellEarnRewardsRewardContractRoute
  '/_shell/earn/fixed/market/$marketAddress': typeof ShellEarnFixedMarketMarketAddressRoute
  '/_shell/earn/vaults/$provider/$vaultAddress': typeof ShellEarnVaultsProviderVaultAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batch-transactions-legal-notice'
    | '/dev'
    | '/seal-engine'
    | '/convert'
    | '/portfolio'
    | '/stake'
    | '/convert/psm'
    | '/convert/trade'
    | '/convert/upgrade'
    | '/earn/expert'
    | '/earn/fixed'
    | '/earn/rewards'
    | '/earn/savings'
    | '/earn/vaults'
    | '/earn/'
    | '/earn/expert/stusds'
    | '/earn/rewards/$rewardContract'
    | '/earn/fixed/market/$marketAddress'
    | '/earn/vaults/$provider/$vaultAddress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/batch-transactions-legal-notice'
    | '/dev'
    | '/seal-engine'
    | '/convert'
    | '/portfolio'
    | '/stake'
    | '/'
    | '/convert/psm'
    | '/convert/trade'
    | '/convert/upgrade'
    | '/earn/expert'
    | '/earn/fixed'
    | '/earn/rewards'
    | '/earn/savings'
    | '/earn/vaults'
    | '/earn'
    | '/earn/expert/stusds'
    | '/earn/rewards/$rewardContract'
    | '/earn/fixed/market/$marketAddress'
    | '/earn/vaults/$provider/$vaultAddress'
  id:
    | '__root__'
    | '/_shell'
    | '/batch-transactions-legal-notice'
    | '/dev'
    | '/seal-engine'
    | '/_shell/convert'
    | '/_shell/portfolio'
    | '/_shell/stake'
    | '/_shell/'
    | '/_shell/convert/psm'
    | '/_shell/convert/trade'
    | '/_shell/convert/upgrade'
    | '/_shell/earn/expert'
    | '/_shell/earn/fixed'
    | '/_shell/earn/rewards'
    | '/_shell/earn/savings'
    | '/_shell/earn/vaults'
    | '/_shell/earn/'
    | '/_shell/earn/expert/stusds'
    | '/_shell/earn/rewards/$rewardContract'
    | '/_shell/earn/fixed/market/$marketAddress'
    | '/_shell/earn/vaults/$provider/$vaultAddress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  BatchTransactionsLegalNoticeRoute: typeof BatchTransactionsLegalNoticeRoute
  DevRoute: typeof DevRoute
  SealEngineRoute: typeof SealEngineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seal-engine': {
      id: '/seal-engine'
      path: '/seal-engine'
      fullPath: '/seal-engine'
      preLoaderRoute: typeof SealEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch-transactions-legal-notice': {
      id: '/batch-transactions-legal-notice'
      path: '/batch-transactions-legal-notice'
      fullPath: '/batch-transactions-legal-notice'
      preLoaderRoute: typeof BatchTransactionsLegalNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/stake': {
      id: '/_shell/stake'
      path: '/stake'
      fullPath: '/stake'
      preLoaderRoute: typeof ShellStakeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/portfolio': {
      id: '/_shell/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof ShellPortfolioRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/convert': {
      id: '/_shell/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ShellConvertRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/earn/': {
      id: '/_shell/earn/'
      path: '/earn'
      fullPath: '/earn/'
      preLoaderRoute: typeof ShellEarnIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/earn/vaults': {
      id: '/_shell/earn/vaults'
      path: '/earn/vaults'
      fullPath: '/earn/vaults'
      preLoaderRoute: typeof ShellEarnVaultsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/earn/savings': {
      id: '/_shell/earn/savings'
      path: '/earn/savings'
      fullPath: '/earn/savings'
      preLoaderRoute: typeof ShellEarnSavingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/earn/rewards': {
      id: '/_shell/earn/rewards'
      path: '/earn/rewards'
      fullPath: '/earn/rewards'
      preLoaderRoute: typeof ShellEarnRewardsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/earn/fixed': {
      id: '/_shell/earn/fixed'
      path: '/earn/fixed'
      fullPath: '/earn/fixed'
      preLoaderRoute: typeof ShellEarnFixedRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/earn/expert': {
      id: '/_shell/earn/expert'
      path: '/earn/expert'
      fullPath: '/earn/expert'
      preLoaderRoute: typeof ShellEarnExpertRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/convert/upgrade': {
      id: '/_shell/convert/upgrade'
      path: '/upgrade'
      fullPath: '/convert/upgrade'
      preLoaderRoute: typeof ShellConvertUpgradeRouteImport
      parentRoute: typeof ShellConvertRoute
    }
    '/_shell/convert/trade': {
      id: '/_shell/convert/trade'
      path: '/trade'
      fullPath: '/convert/trade'
      preLoaderRoute: typeof ShellConvertTradeRouteImport
      parentRoute: typeof ShellConvertRoute
    }
    '/_shell/convert/psm': {
      id: '/_shell/convert/psm'
      path: '/psm'
      fullPath: '/convert/psm'
      preLoaderRoute: typeof ShellConvertPsmRouteImport
      parentRoute: typeof ShellConvertRoute
    }
    '/_shell/earn/rewards/$rewardContract': {
      id: '/_shell/earn/rewards/$rewardContract'
      path: '/$rewardContract'
      fullPath: '/earn/rewards/$rewardContract'
      preLoaderRoute: typeof ShellEarnRewardsRewardContractRouteImport
      parentRoute: typeof ShellEarnRewardsRoute
    }
    '/_shell/earn/expert/stusds': {
      id: '/_shell/earn/expert/stusds'
      path: '/stusds'
      fullPath: '/earn/expert/stusds'
      preLoaderRoute: typeof ShellEarnExpertStusdsRouteImport
      parentRoute: typeof ShellEarnExpertRoute
    }
    '/_shell/earn/vaults/$provider/$vaultAddress': {
      id: '/_shell/earn/vaults/$provider/$vaultAddress'
      path: '/$provider/$vaultAddress'
      fullPath: '/earn/vaults/$provider/$vaultAddress'
      preLoaderRoute: typeof ShellEarnVaultsProviderVaultAddressRouteImport
      parentRoute: typeof ShellEarnVaultsRoute
    }
    '/_shell/earn/fixed/market/$marketAddress': {
      id: '/_shell/earn/fixed/market/$marketAddress'
      path: '/market/$marketAddress'
      fullPath: '/earn/fixed/market/$marketAddress'
      preLoaderRoute: typeof ShellEarnFixedMarketMarketAddressRouteImport
      parentRoute: typeof ShellEarnFixedRoute
    }
  }
}

interface ShellConvertRouteChildren {
  ShellConvertPsmRoute: typeof ShellConvertPsmRoute
  ShellConvertTradeRoute: typeof ShellConvertTradeRoute
  ShellConvertUpgradeRoute: typeof ShellConvertUpgradeRoute
}

const ShellConvertRouteChildren: ShellConvertRouteChildren = {
  ShellConvertPsmRoute: ShellConvertPsmRoute,
  ShellConvertTradeRoute: ShellConvertTradeRoute,
  ShellConvertUpgradeRoute: ShellConvertUpgradeRoute,
}

const ShellConvertRouteWithChildren = ShellConvertRoute._addFileChildren(
  ShellConvertRouteChildren,
)

interface ShellEarnExpertRouteChildren {
  ShellEarnExpertStusdsRoute: typeof ShellEarnExpertStusdsRoute
}

const ShellEarnExpertRouteChildren: ShellEarnExpertRouteChildren = {
  ShellEarnExpertStusdsRoute: ShellEarnExpertStusdsRoute,
}

const ShellEarnExpertRouteWithChildren = ShellEarnExpertRoute._addFileChildren(
  ShellEarnExpertRouteChildren,
)

interface ShellEarnFixedRouteChildren {
  ShellEarnFixedMarketMarketAddressRoute: typeof ShellEarnFixedMarketMarketAddressRoute
}

const ShellEarnFixedRouteChildren: ShellEarnFixedRouteChildren = {
  ShellEarnFixedMarketMarketAddressRoute:
    ShellEarnFixedMarketMarketAddressRoute,
}

const ShellEarnFixedRouteWithChildren = ShellEarnFixedRoute._addFileChildren(
  ShellEarnFixedRouteChildren,
)

interface ShellEarnRewardsRouteChildren {
  ShellEarnRewardsRewardContractRoute: typeof ShellEarnRewardsRewardContractRoute
}

const ShellEarnRewardsRouteChildren: ShellEarnRewardsRouteChildren = {
  ShellEarnRewardsRewardContractRoute: ShellEarnRewardsRewardContractRoute,
}

const ShellEarnRewardsRouteWithChildren =
  ShellEarnRewardsRoute._addFileChildren(ShellEarnRewardsRouteChildren)

interface ShellEarnVaultsRouteChildren {
  ShellEarnVaultsProviderVaultAddressRoute: typeof ShellEarnVaultsProviderVaultAddressRoute
}

const ShellEarnVaultsRouteChildren: ShellEarnVaultsRouteChildren = {
  ShellEarnVaultsProviderVaultAddressRoute:
    ShellEarnVaultsProviderVaultAddressRoute,
}

const ShellEarnVaultsRouteWithChildren = ShellEarnVaultsRoute._addFileChildren(
  ShellEarnVaultsRouteChildren,
)

interface ShellRouteChildren {
  ShellConvertRoute: typeof ShellConvertRouteWithChildren
  ShellPortfolioRoute: typeof ShellPortfolioRoute
  ShellStakeRoute: typeof ShellStakeRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellEarnExpertRoute: typeof ShellEarnExpertRouteWithChildren
  ShellEarnFixedRoute: typeof ShellEarnFixedRouteWithChildren
  ShellEarnRewardsRoute: typeof ShellEarnRewardsRouteWithChildren
  ShellEarnSavingsRoute: typeof ShellEarnSavingsRoute
  ShellEarnVaultsRoute: typeof ShellEarnVaultsRouteWithChildren
  ShellEarnIndexRoute: typeof ShellEarnIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellConvertRoute: ShellConvertRouteWithChildren,
  ShellPortfolioRoute: ShellPortfolioRoute,
  ShellStakeRoute: ShellStakeRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellEarnExpertRoute: ShellEarnExpertRouteWithChildren,
  ShellEarnFixedRoute: ShellEarnFixedRouteWithChildren,
  ShellEarnRewardsRoute: ShellEarnRewardsRouteWithChildren,
  ShellEarnSavingsRoute: ShellEarnSavingsRoute,
  ShellEarnVaultsRoute: ShellEarnVaultsRouteWithChildren,
  ShellEarnIndexRoute: ShellEarnIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  BatchTransactionsLegalNoticeRoute: BatchTransactionsLegalNoticeRoute,
  DevRoute: DevRoute,
  SealEngineRoute: SealEngineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
