labels:
  app: ${APP_NAME}
selectorLabels:
  app: ${APP_NAME}

ingress:
  enabled: true
  host: ${HOSTNAME}
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'

image:
  repository: ${ECR_REGISTRY}/tarmac-prod
  tag: ${IMAGE_TAG}
  pullPolicy: Always

service:
  enabled: true
  name: ${APP_NAME}
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  tls:
    enabled: true
    issuerName: cloudflare

deployment:
  enabled: true
  ports:
    - containerPort: 80
      name: http
      protocol: TCP

resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75

readinessProbe:
  tcpSocket:
    port: 80
livenessProbe:
  tcpSocket:
    port: 80

serviceAccount:
  create: false

podAnnotations:
  reloader.stakater.com/auto: 'true'
