name: CI - Untrusted (Dependabot Safe)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  actions: write  # Needed to upload artifacts

concurrency:
  group: ci-untrusted-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
        pnpm-version: [9.9.0]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm-version }}
      
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      
      - name: Build packages
        run: pnpm build:packages
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
      
      - name: Build webapp
        run: pnpm -F webapp build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
      
      - name: Lint and Type Check
        run: |
          pnpm lint
          pnpm typecheck
      
      - name: Test utils package (no secrets needed)
        run: pnpm test:utils
      
      # Upload build artifacts for trusted workflow
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.run_id }}
          path: |
            packages/*/dist
            apps/webapp/dist
          retention-days: 1
      
      # Create a metadata file with PR information
      - name: Create metadata
        run: |
          mkdir -p metadata
          echo '{
            "pr_number": ${{ github.event.pull_request.number }},
            "sha": "${{ github.event.pull_request.head.sha }}",
            "base_ref": "${{ github.event.pull_request.base.ref }}",
            "head_ref": "${{ github.event.pull_request.head.ref }}",
            "run_id": "${{ github.run_id }}"
          }' > metadata/pr-info.json
      
      - name: Upload metadata
        uses: actions/upload-artifact@v4
        with:
          name: metadata-${{ github.run_id }}
          path: metadata/
          retention-days: 1