name: Dependabot PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Basic validation for Dependabot PRs
  validate-dependabot:
    name: Validate Dependabot PR
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate dependency changes
        run: |
          echo "🔍 Validating Dependabot PR changes..."
          
          # Check if only dependency files were changed
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          
          # Allowed patterns for Dependabot
          ALLOWED_PATTERNS=(
            "package.json"
            "package-lock.json"
            "pnpm-lock.yaml"
            "yarn.lock"
            "**/*.d.ts"
          )
          
          SUSPICIOUS_FILES=()
          for file in $CHANGED_FILES; do
            if [[ -n "$file" ]]; then
              ALLOWED=false
              for pattern in "${ALLOWED_PATTERNS[@]}"; do
                if [[ "$file" == $pattern ]] || [[ "$file" =~ ^.*\.d\.ts$ ]]; then
                  ALLOWED=true
                  break
                fi
              done
              if [[ "$ALLOWED" == false ]]; then
                SUSPICIOUS_FILES+=("$file")
              fi
            fi
          done
          
          if [[ ${#SUSPICIOUS_FILES[@]} -gt 0 ]]; then
            echo "❌ Suspicious files detected:"
            printf '%s\n' "${SUSPICIOUS_FILES[@]}"
            exit 1
          fi
          
          echo "✅ Only dependency files were changed"

      - name: Check for security issues
        run: |
          echo "🔒 Running security checks..."
          
          # Check for hardcoded secrets
          if grep -r "TENDERLY_API_KEY.*[A-Za-z0-9]" .github/workflows/; then
            echo "❌ Hardcoded API key detected"
            exit 1
          fi
          
          # Check for dangerous patterns
          if grep -r "echo.*secrets" .github/workflows/; then
            echo "❌ Potential secret exposure detected"
            exit 1
          fi
          
          echo "✅ No obvious security issues detected"

      - name: Run npm audit
        run: |
          echo "📦 Running npm audit..."
          npm audit --audit-level=moderate || {
            echo "❌ Security vulnerabilities found"
            exit 1
          }
          echo "✅ No moderate or higher vulnerabilities found"

      - name: Build validation
        run: |
          echo "🔨 Validating build..."
          
          # Install dependencies
          npm ci
          
          # Try to build (without running tests that need secrets)
          npm run build:packages || {
            echo "❌ Build failed"
            exit 1
          }
          
          echo "✅ Build validation passed"

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ✅ Dependabot PR Validation Complete
            
            This PR has passed initial validation and will now trigger the full test suite with secrets access.
            
            **Validated:**
            - ✅ Only dependency files changed
            - ✅ No security issues detected
            - ✅ No moderate+ vulnerabilities
            - ✅ Build validation passed
            
            The trusted workflow will now run with full access to secrets for comprehensive testing.`
            })

  # Trigger the trusted workflow for comprehensive testing
  trigger-trusted-workflow:
    name: Trigger Trusted Workflow
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    needs: validate-dependabot
    steps:
      - name: Trigger trusted workflow
        run: |
          echo "🚀 Triggering trusted workflow for comprehensive testing..."
          echo "This will run the full test suite with access to secrets" 