name: Webapp E2E tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        include:
          - test: upgrade.spec
            vnet: true
            chain: mainnet
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build:packages
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - run: pnpm -F webapp exec playwright install --with-deps chromium

      - name: Setup VNet (if required)
        if: ${{ matrix.vnet }}
        run: |
          pnpm run vnet:fork:ci ${{ matrix.chain }}
        env:
          TENDERLY_API_KEY: ${{ secrets.TENDERLY_API_KEY }}

      - name: Run E2E Test
        run: pnpm run e2e:no-vnet ${{ matrix.test }}
        env:
          TEST_CHAIN: ${{ matrix.chain }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          VITE_ENV_NAME: development
          VITE_TERMS_LINK: '[{"url":"https://legal-terms","name":"Terms of Use"}]'
          VITE_BATCH_TX_ENABLED: 'true'

      - name: Teardown VNet (if required)
        if: ${{always() && matrix.vnet}}
        run: |
          pnpm run vnet:delete:ci
        env:
          TENDERLY_API_KEY: ${{ secrets.TENDERLY_API_KEY }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.test }}
          path: apps/webapp/playwright-report/
          retention-days: 30
